sonar.organization=adeo
sonar.projectKey=mongo2pg
sonar.sources=src/
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.rust.cargotoml=./Cargo.toml
sonar.rust.cargolock=./Cargo.lock
sonar.rust.tests.reportPath=target/sonar/report.xml
sonar.rust.coverage.reportPaths=target/sonar/coverage.xml
sonar.rust.clippy.reportPaths=target/sonar/clippy.json
sonar.rust.cargo-audit.reportPaths=target/sonar/audit.json