version: "3"

vars:
  URI: "mongodb://user:pass@localhost:2717/?authSource=admin"
  RESULTS_DIR: results
  BIN: "{{.ROOT_DIR}}/target/debug/mongo2pg"
  DATABASES: >-
    sample_airbnb
    sample_analytics
    sample_geospatial
    sample_mflix
    sample_supplies
    sample_training
    sample_weatherdata
    retail

tasks:
  build:
    desc: Build the mongo2pg binary (debug)
    cmds:
      - cargo build
    sources:
      - src/**/*.rs
      - Cargo.toml
      - Cargo.lock
    generates:
      - target/debug/mongo2pg

  infer:
    desc: Infer schemas for all sample databases, generate SQL DDL into {{.RESULTS_DIR}}/infer/
    silent: true
    deps: [build]
    vars:
      OUT: "{{.RESULTS_DIR}}/infer"
    cmds:
      - mkdir -p "{{.OUT}}"
      - |
        for db in {{.DATABASES}}
        do
          echo "📁 init $db"
          "{{.BIN}}" init --project-base "{{.OUT}}" --project-name "$db" --source-uri "{{.URI}}"
          echo "📐 infer $db"
          "{{.BIN}}" infer --source-uri "{{.URI}}" -c "{{.OUT}}/$db/config/$db.toml" --no-output 2>/dev/null
        done
      - echo "👉 results in {{.OUT}}"

  infer-with-jsonb:
    desc: Infer schemas with --jsonb 🪆, generate SQL DDL and HTML report into {{.RESULTS_DIR}}/infer-with-jsonb/
    silent: true
    deps: [build]
    vars:
      OUT: "{{.RESULTS_DIR}}/infer-with-jsonb"
    cmds:
      - mkdir -p "{{.OUT}}"
      - |
        for db in {{.DATABASES}}
        do
          echo "📁 init $db"
          "{{.BIN}}" init --project-base "{{.OUT}}" --project-name "$db" --source-uri "{{.URI}}"
          echo "📐 infer $db"
          "{{.BIN}}" infer --source-uri "{{.URI}}" -c "{{.OUT}}/$db/config/$db.toml" --jsonb --no-output 2>/dev/null
        done
      - echo "👉 results in {{.OUT}}"

  make-tutorial:
    desc: Create tutorial schemas
    silent: true
    deps: [build]
    vars:
      OUT: "tutorial/base"
      DB: "retail"
    cmds:
      - |
        echo "📁 init {{.DB}}"
        "{{.BIN}}" init --project-base "{{.OUT}}" --project-name "{{.DB}}" --source-uri "{{.URI}}"
        echo "📐 infer {{.DB}}"
        "{{.BIN}}" infer --source-uri "{{.URI}}" -c "{{.OUT}}/{{.DB}}/config/{{.DB}}.toml" --jsonb --no-output 2>/dev/null

